/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#b0c6f9',
        'inverse-surface': '#31302b',
        outline: '#7a756d',
        'on-surface': '#1a1c1e',
        'on-primary-container': '#2a1700',
        'surface-container-highest': '#e5e2dc',
        'on-secondary-fixed': '#1a1c1e',
        'on-background': '#1a1c1e',
        'surface-container-high': '#ebe7e1',
        'on-tertiary': '#ffffff',
        'on-error-container': '#410002',
        'on-secondary-container': '#251a04',
        'inverse-on-surface': '#f5f0e9',
        'secondary-container': '#f6dfbb',
        'on-primary-fixed-variant': '#5d4201',
        'on-secondary': '#ffffff',
        secondary: '#6c5c3f',
        surface: '#fdfcfb',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#082008',
        'on-secondary-fixed-variant': '#454747',
        'surface-container-low': '#f7f4ee',
        error: '#ba1a1a',
        background: '#ffffff',
        'on-primary-fixed': '#261900',
        'surface-container': '#f1ede7',
        'inverse-primary': '#ffb95e',
        tertiary: '#4a6546',
        'error-container': '#ffdad6',
        'surface-variant': '#e7e0d6',
        'primary-container': '#ffddaa',
        'tertiary-container': '#ccebc4',
        'secondary-fixed-dim': '#c6c6c7',
        'surface-dim': '#ded8d3',
        primary: '#1e3a8a',
        'tertiary-fixed': '#d8e2ff',
        'on-surface-variant': '#49453e',
        'secondary-fixed': '#e2e2e2',
        'surface-bright': '#fdfcfb',
        'surface-tint': '#1e3a8a',
        'primary-fixed': '#ffdea5',
        'on-tertiary-fixed': '#001a41',
        'on-tertiary-fixed-variant': '#304671',
        'primary-fixed-dim': '#e9c176',
        'outline-variant': '#cbc6bd',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'section-gap-mobile': '64px',
        unit: '8px',
        gutter: '24px',
        'container-padding-desktop': '80px',
        'section-gap-desktop': '120px',
      },
      fontFamily: {
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-sm': ['EB Garamond', 'serif'],
        'label-caps': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['EB Garamond', 'serif'],
        'display-lg-mobile': ['EB Garamond', 'serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'display-lg': ['EB Garamond', 'serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '1.2', letterSpacing: '0.15em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0.01em', fontWeight: '400' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
