/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#b0c6f9',
        'inverse-surface': '#e5e2e1',
        outline: '#a89b8a',
        'on-surface': '#e5e2e1',
        'on-primary-container': '#4e3700',
        'surface-container-highest': '#3f3f3d',
        'on-secondary-fixed': '#1a1c1c',
        'on-background': '#e5e2e1',
        'surface-container-high': '#343432',
        'on-tertiary': '#173059',
        'on-error-container': '#ffdad6',
        'on-secondary-container': '#b4b5b5',
        'inverse-on-surface': '#313030',
        'secondary-container': '#454747',
        'on-primary-fixed-variant': '#5d4201',
        'on-secondary': '#2f3131',
        secondary: '#cfced0',
        surface: '#1a1a1a',
        'on-primary': '#412d00',
        'on-error': '#690005',
        'surface-container-lowest': '#151515',
        'on-tertiary-container': '#233a65',
        'on-secondary-fixed-variant': '#454747',
        'surface-container-low': '#252423',
        error: '#ffb4ab',
        background: '#1a1a1a',
        'on-primary-fixed': '#261900',
        'surface-container': '#2b2a29',
        'inverse-primary': '#775a19',
        tertiary: '#b0c6f9',
        'error-container': '#93000a',
        'surface-variant': '#3f3f3d',
        'primary-container': '#c5a059',
        'tertiary-container': '#8fa5d6',
        'secondary-fixed-dim': '#c6c6c7',
        'surface-dim': '#1a1a1a',
        primary: '#e9c176',
        'tertiary-fixed': '#d8e2ff',
        'on-surface-variant': '#ddd1c2',
        'secondary-fixed': '#e2e2e2',
        'surface-bright': '#474745',
        'surface-tint': '#e9c176',
        'primary-fixed': '#ffdea5',
        'on-tertiary-fixed': '#001a41',
        'on-tertiary-fixed-variant': '#304671',
        'primary-fixed-dim': '#e9c176',
        'outline-variant': '#61584a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'section-gap-mobile': '64px',
        unit: '8px',
        gutter: '24px',
        'container-padding-desktop': '80px',
        'section-gap-desktop': '120px',
      },
      fontFamily: {
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-sm': ['EB Garamond', 'serif'],
        'label-caps': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['EB Garamond', 'serif'],
        'display-lg-mobile': ['EB Garamond', 'serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'display-lg': ['EB Garamond', 'serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '1.2', letterSpacing: '0.15em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0.01em', fontWeight: '400' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
